# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-resources/floating_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWidgetWindow(object):
    def setupUi(self, PlotWidgetWindow):
        PlotWidgetWindow.setObjectName("PlotWidgetWindow")
        PlotWidgetWindow.resize(648, 494)
        self.centralwidget = QtWidgets.QWidget(PlotWidgetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_window = PlotWidget(self.centralwidget)
        self.plot_window.setObjectName("plot_window")
        self.verticalLayout_2.addWidget(self.plot_window)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ttcf_button = QtWidgets.QRadioButton(self.centralwidget)
        self.ttcf_button.setChecked(False)
        self.ttcf_button.setObjectName("ttcf_button")
        self.horizontalLayout.addWidget(self.ttcf_button)
        self.msd_button = QtWidgets.QRadioButton(self.centralwidget)
        self.msd_button.setChecked(True)
        self.msd_button.setObjectName("msd_button")
        self.horizontalLayout.addWidget(self.msd_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.x_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.x_checkbox.setChecked(True)
        self.x_checkbox.setObjectName("x_checkbox")
        self.horizontalLayout_2.addWidget(self.x_checkbox)
        self.y_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.y_checkbox.setObjectName("y_checkbox")
        self.horizontalLayout_2.addWidget(self.y_checkbox)
        self.z_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.z_checkbox.setObjectName("z_checkbox")
        self.horizontalLayout_2.addWidget(self.z_checkbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        PlotWidgetWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotWidgetWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PlotWidgetWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotWidgetWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWidgetWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(PlotWidgetWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PlotWidgetWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWidgetWindow)

    def retranslateUi(self, PlotWidgetWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWidgetWindow.setWindowTitle(_translate("PlotWidgetWindow", "Real-time plot"))
        self.ttcf_button.setText(_translate("PlotWidgetWindow", "TTCF"))
        self.msd_button.setText(_translate("PlotWidgetWindow", "Mean-square displacement"))
        self.label.setText(_translate("PlotWidgetWindow", "Coordinates to plot"))
        self.x_checkbox.setText(_translate("PlotWidgetWindow", "x"))
        self.y_checkbox.setText(_translate("PlotWidgetWindow", "y"))
        self.z_checkbox.setText(_translate("PlotWidgetWindow", "z"))
        self.menuFile.setTitle(_translate("PlotWidgetWindow", "File"))
        self.actionQuit.setText(_translate("PlotWidgetWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("PlotWidgetWindow", "Ctrl+Q"))
from pyqtgraph import PlotWidget
